require 'rubygems'
require 'capybara'
require 'capybara/dsl'
require 'capybara/poltergeist'

Capybara.default_driver = :poltergeist
Capybara.run_server = false

Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, phantomjs_options: ['--load-images=false', '--disk-cache=false'])
end

class FacebookScapper
	include Capybara::DSL
	HOST = "https://www.facebook.com"
	LOGIN_URL = "/login.php?login_attempt=1&lwv=110"
	FRIENDS_URL = "/friends?source_ref=pb_friends_tl"
	MUTUAL_URL = "/friends_mutual"

	def initialize(username, user_pass)
		@email = username
		@password = user_pass
	end

	def authenticate
		visit(HOST + LOGIN_URL)
		fill_in "email", with: @email
		fill_in "pass", with: @password
		find('button[name="login"]').click
	end

	def me
		if @me == nil
			visit(HOST)
			find("a[title='Profile']").click
			@me = Person.new
			@me.id = JSON(find("#pagelet_timeline_main_column")['data-gt'])["profile_owner"]
			@me.name = find("span[id='fb-timeline-cover-name']").text
			@me.link = HOST + current_path
			puts 'Person me'
			puts @me.to_json
		end
		@me
	end

	def my_friends
		visit(me.link + FRIENDS_URL)
		friend_number = find("a[name='All Friends']").find('span:nth-of-type(2)').text
		friends_cards = find_all("ul[data-pnref='friends'] > li")
		end_friends = find_all(".uiHeaderTitle")
		until end_friends.size > 1 do
			page.execute_script "window.scrollBy(0,10000)"
			sleep 0.5
			end_friends = find_all(".uiHeaderTitle")
			friends_cards = find_all("ul[data-pnref='friends'] > li")
		end
		puts "Friends found #{friends_cards.size}"
		i = 1
		@friends = parse_cards(friends_cards).map do |p| 
			puts "Element #{i}/#{friends_cards.size}"
			i += 1
			p.mutual_friends = mutual_friends p.id, p.name 
		end
	end

	def parse_cards(cards)
		cards.map do |element|
			p = Person.new
			p.id = element.find("[data-flloc='profile_browser']")['data-profileid']
			p.name = element.find('.fcb > a').text
			p.link = element.find('.fcb > a')['href']
			p
		end
	end

	def to_neo4j
		script = "
		//---------------------------- <br/>
		// Script for: Neo4j <br/>
		// Generated by: Baby Owl - https://github.com/eduardo-salazar/bowl <br/>
		// ---------------------------- <br/>
		// Import direct connections<br/>
		//---------------------------- <br/>"

		script += "CREATE (n:Person { id: #{@me.id}, name : '#{@me.name}', link : '#{@me.link}' }); <br/>"

		@friends.map do |person|
			script += "CREATE (n:Person { id: #{person.id}, name : '#{person.name}', link : '#{person.link}' }); <br/>"
			script += "MATCH (a:Person),(b:Person) <br/>
			WHERE a.id = #{@me.id} AND b.id = #{person.id} <br/>
			CREATE (a)-[r:IS_FRIEND_WITH]->(b) <br/>
			RETURN r; <br/>"
		end

		@friends.map do |person|
			person.mutual_friends.map do |mutual|
				script += "MATCH (a:Person),(b:Person) <br/>
				WHERE a.id = #{person.id} AND b.id = #{mutual.id} <br/>
				CREATE (a)-[r:IS_FRIEND_WITH]->(b) <br/>
				RETURN r; <br/>"
			end
		end

		script
	end

	def mutual_friends(friend_id, friend_name)
		visit(HOST + '/' + friend_id + MUTUAL_URL)
		begin
			friend_number = find("a[name='Mutual Friends']").find('span:nth-of-type(2)').text
			friends_cards = find_all("ul[data-pnref='friends'] > li")
			end_friends = find_all(".uiHeaderTitle")
			until end_friends.size > 1 do
				page.execute_script "window.scrollBy(0,10000)"
				sleep 0.5
				end_friends = find_all(".uiHeaderTitle")
				friends_cards = find_all("ul[data-pnref='friends'] > li")
			end
			puts "Mutual friends with #{friend_name} = #{friends_cards.size}"
			parse_cards friends_cards
		rescue Capybara::ElementNotFound => e
			puts "Mutual friends with #{friend_name} = 0"
			Array.new
		end
	end

	def get(friend)
	end

	def search(friend_name)
	end

	def agent
		@agent
	end

end
